version: '3'

services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=taxi
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - "8080:8080"
